version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST: localhost
      KAFKA_ZOOKEEPER_CONNECT: zokeeper:2181
      KAFKA_CREATE_TOPICS: